import type { Metadata } from "next";
import { Inter, Poppins } from "next/font/google";
import ClientSessionProvider from "@/components/session";
import { CartProvider } from "@/contexts/CartContext";
import { WishlistProvider } from "@/contexts/WishlistContext";
import { AOSInit } from "@/components/AOSInit";
import { Toaster } from "sonner";
import "./globals.css";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  display: "swap",
});

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-poppins",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.variable} ${inter.variable} antialiased w-full font-poppins`}
      >
        <ClientSessionProvider>
          <CartProvider>
            <WishlistProvider>
              <AOSInit />
              <div className="max-w-[2560px] mx-auto inner-body">
                {children}
                <Toaster position="top-center" />
              </div>
            </WishlistProvider>
          </CartProvider>
        </ClientSessionProvider>
      </body>
    </html>
  );
}
